# Generated by Django 3.2.5 on 2021-08-02 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('description', models.TextField(default='Нет описания', verbose_name='Описание')),
                ('creation_date', models.DateField(default='Нет даты создания', verbose_name='Дата создания')),
                ('budget', models.FloatField(default='Нет общего бюджета компании', verbose_name='Бюджет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Открыта ли компания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Company_Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='company-photo')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='ФИО сотрудника')),
                ('position', models.TextField(choices=[('IT', 'IT Department'), ('FD', 'Financial Department'), ('AN', 'Analyst'), ('AD', 'Advertising Department'), ('DC', 'Deputy Chief'), ('CH', 'Chief')], verbose_name='Должность')),
                ('is_active_now', models.BooleanField(default=True, verbose_name='Работает ли в данный мосент')),
                ('photo', models.ImageField(upload_to='personal-photo')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+375000000000'. Up to 12 digits allowed.", regex='^\\+?1?\\d{12,12}$')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='company_pictures',
            name='photo_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.personal'),
        ),
    ]
