# Generated by Django 3.2.5 on 2021-08-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210802_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_pictures',
            name='photo_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.company'),
        ),
    ]
